### ISSUE TITLE
Add a config file line to disable merging?

### ISSUE THREAD

**Issue by RidleyofZebes** [cyb3rdoc/ez-nvr#11]
The individual video files are working great, but for some reason when it merges them it loses much of what it had, (most likely the fault of my gimpy server hardware, alas) resulting in video files that are only 45min to 16hr long instead of the full 24 hour video. A simple option to disable the merging would be appreciated.

**Comment by cyb3rdoc** [comment]
That's doable however will require a bit overhaul to current code. So it might take some time to implement.

**Comment by cyb3rdoc** [comment]
I updated the code and added option to enable/disable concatenation via config file. Updated code is in `dev` branch and docker image uses `dev` tag. Check `dev` docker image and let me know if this fixes your issues. Default option is 'true' so you should set it to 'false' in config file.
