### ISSUE TITLE
{rtsp_url} issues

### ISSUE THREAD

**Issue by matbor** [cyb3rdoc/ez-nvr#2]
https://github.com/cyb3rdoc/ez-nvr/blob/1db3367af867d6612020f3d1675ddf3c123cf221/src/app/modules/recording.py#L36

Had to add `\”` in my version for the part `{rtsp_url}`, as I had trouble with long URL’s that had multiple `&` symbols in the URL.

ie. `\”{rtsp_url} \”`

**Comment by cyb3rdoc** [comment]
Thanks for bringing this up. The `&` in the rstp URL must be breaking the ffmpeg command. I will try to implement the fix.

**Comment by cyb3rdoc** [comment]
I updated the code to address another issue and have added potential fix for this too. Currently I am testing it so updated code is in `dev` branch and docker image uses `dev` tag. Check and let me know if this fixes your issues.

**Comment by cyb3rdoc** [comment]
The latest commit "e788ae1" should resolve this issue as input sanitization is implemented now. You can reopen the issue if still facing problem.
