### ISSUE TITLE
SIGINT not working for me.

### ISSUE THREAD

**Issue by matbor** [cyb3rdoc/ez-nvr#3]
https://github.com/cyb3rdoc/ez-nvr/blob/1db3367af867d6612020f3d1675ddf3c123cf221/src/app/modules/recording.py#L47

FYI, when running in docker-compose, `SIGKILL` seems to work better at killing the process than `SIGINT` for me.

https://www.gnu.org/software/libc/manual/html_node/Termination-Signals.html

**Comment by cyb3rdoc** [comment]
I will check and update in code if required.

**Comment by cyb3rdoc** [comment]
I updated the code to address another issue and SIGINIT/SIGKILL is out of scope now, so I am closing this issue.
Currently I am testing the code so it's in `dev` branch and docker image uses `dev` tag. Check and let me know if you get any issues.
