### ISSUE TITLE
play video files on IOS

### ISSUE THREAD

**Issue by stepir** [cyb3rdoc/ez-nvr#4]
Hi 

thanks for this project!

I'm currently testing to record the RTSP output of some EZVIZ camera (in example this one is coming from a C6N). The output is reproducible fine with VLC but not natively on IOS - which would prevent the idea I had of using this tool (looking directly at the video files via filebrowser).

![image](https://github.com/cyb3rdoc/ez-nvr/assets/36472935/4d3e4015-b6be-4e3b-aea9-b7f81c230a5c)

Currently I'm using `camera_codec: copy` but also camera_codec: libx264 produce the same. 

I'm attaching a video file example also.
[2023-09-10T20-09-22.mkv.zip](https://github.com/cyb3rdoc/ez-nvr/files/12569851/2023-09-10T20-09-22.mkv.zip)

Do you have any recommendations on how to get the output natively reproducible on IOS?

**Comment by stepir** [comment]
end up in stop using filebrowser and move it to plex - the video files will then be transcoded on the fly

**Comment by cyb3rdoc** [comment]
Hi. The `copy` coded just copies output from your camera without any transcoding. You will have same issue if you use `firefox` on PC. This is a web browser issue as it do not correctly identifies mastroka file format. But as mentioned, plex or jellyfin can potentially resolve this.
